### ISSUE TITLE
More details in Readme.md

### ISSUE THREAD

**Issue by srizzling** [SmartBear/ready-api-jenkins-plugin#1]
Hey, this plugin looks interesting, but requires me to look into the code, to figure out what it does. Would be useful to have some documenation about what it can do. If would like, I can commit some time to do this.

**Comment by renatoathaydes** [comment]
Hi, Thank you for getting in touch.

We have only added information that is useful for developers, but not information for users, in the README page.

Feel free to submit a PR! Otherwise, when our doc team has some time, they will put something up about this on our website.
